/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useMemo } from 'react';
import { useSearchParams } from 'react-router-dom';
import { DatabaseState, getCustomerBalances, CustomerBalance } from '../lib/db';
import { formatCurrency, formatPhoneNumberForUrl, getGeminiHeaders, triggerHaptic } from '../lib/utils';
import { useFirebase } from '../lib/FirebaseContext';
import { 
  Send, 
  MessageSquare, 
  Sparkles, 
  Copy, 
  Check, 
  AlertCircle,
  HelpCircle,
  Clock,
  User,
  ExternalLink,
  RefreshCw
} from 'lucide-react';

interface RemindersTabProps {
  db: DatabaseState;
}

export function RemindersTab({ db }: RemindersTabProps) {
  const { profile } = useFirebase();
  const [searchParams] = useSearchParams();
  const queryCustomerId = searchParams.get('id');
  const [hasAutoGeneratedFor, setHasAutoGeneratedFor] = useState<string | null>(null);

  const [selectedCustomerId, setSelectedCustomerId] = useState<string>('');
  const [selectedTemplateId, setSelectedTemplateId] = useState<string | null>(null);
  const [tone, setTone] = useState<'friendly' | 'firm' | 'formal' | 'urgent'>('friendly');
  const [customNotes, setCustomNotes] = useState<string>('');
  
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedMessage, setGeneratedMessage] = useState('');
  const [generatedAdvice, setGeneratedAdvice] = useState('');
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  const activeDebtors = useMemo(() => {
    return getCustomerBalances(db).filter(b => b.remainingDebt > 0);
  }, [db]);

  // Set selected debtor based on URL or default to first debtor
  React.useEffect(() => {
    if (queryCustomerId && activeDebtors.some(b => b.customer.id === queryCustomerId)) {
      setSelectedCustomerId(queryCustomerId);
    } else if (activeDebtors.length > 0 && !selectedCustomerId) {
      setSelectedCustomerId(activeDebtors[0].customer.id);
    }
  }, [activeDebtors, queryCustomerId, selectedCustomerId]);

  const selectedDebtorBalance = useMemo(() => {
    return activeDebtors.find(d => d.customer.id === selectedCustomerId) || null;
  }, [activeDebtors, selectedCustomerId]);

  // 1. Predefined standard templates (قوالب سريعة جاهزة مصنفة)
  const templates = useMemo(() => {
    if (!selectedDebtorBalance) return [];
    const name = selectedDebtorBalance.customer.name;
    const amountStr = formatCurrency(selectedDebtorBalance.remainingDebt);
    const delName = profile?.delegateName || 'عبدالرحمن كنعان';
    const isOverdue = selectedDebtorBalance.isOverdue;
    
    const collection = [
      {
        id: 'tmpl-friendly',
        category: 'ودي',
        name: 'تذكير ودي بسيط',
        text: `السلام عليكم ورحمة الله وبركاته أخ ${name}، أتمنى أن تكون بصحة وعافية. تذكير لطيف وسريع بأن رصيد حسابك المتبقي المعتمد لدينا يبلغ ${amountStr}. يرجى مراجعته وتسديده عند تيسر الأمر لكم. شكراً جزيلاً لتعاملك الطيب وثقتك الغالية.`,
      },
      {
        id: 'tmpl-formal',
        category: 'رسمي',
        name: 'إخطار مالي رسمي',
        text: `السادة ${name} المحترمين، تحية طيبة وبعد.. نفيدكم علماً بأن الرصيد المستحق في ذمتكم لصالح مؤسستنا قد بلغ ${amountStr}${selectedDebtorBalance.customer.createdAt ? ` والمقيد بتاريخ ${selectedDebtorBalance.customer.createdAt.split('T')[0]}` : ''}. نأمل منكم التكرم بجدولة سداد هذا المبلغ في أقرب وقت ممكن لاستمرار تزويدكم بالخدمات والبضائع كالمعتاد. شاكرين تعاونكم.`,
      },
      {
        id: 'tmpl-followup',
        category: 'متابعة',
        name: 'متابعة بضاعة مستلمة',
        text: `السلام عليكم أخي ${name}، بخصوص طلبية البضاعة الأخيرة، يبلغ المتبقي المالي منها ${amountStr}. نرجو تجهيز المبلغ ليتسنى لمندوبنا الاستلام أو تفضلكم بالتحويل. جزاكم الله خيراً.`,
      }
    ];

    if (isOverdue) {
      const lastActiveDate = selectedDebtorBalance.lastActive ? selectedDebtorBalance.lastActive.split('T')[0] : '';
      collection.unshift({
        id: 'tmpl-urgent',
        category: 'مستعجل',
        name: 'إنذار تأخير سداد',
        text: `تنبيه عاجل: الأخ ${name}، نود إعلامكم بأن مبلغ ${amountStr} قد تجاوز تاريخ الاستحقاق المتفق عليه (تاريخ العملية: ${lastActiveDate}). نرجو سداد المتأخرات فوراً لتجنب إيقاف التعاملات مؤقتاً أو اتخاذ إجراءات إدارية أخرى. ننتظر ردكم خلال اليوم لتسوية الوضع المحاسبي.`,
      });
    }

    return collection;
  }, [selectedDebtorBalance, profile]);

  const [activeCategory, setActiveCategory] = useState<string>('الكل');
  
  const filteredTemplates = useMemo(() => {
    if (activeCategory === 'الكل') return templates;
    return templates.filter(t => t.category === activeCategory);
  }, [templates, activeCategory]);

  const categories = useMemo(() => {
    const cats = ['الكل', ...new Set(templates.map(t => t.category))];
    return cats;
  }, [templates]);

  const handleApplyTemplate = (templateId: string, text: string) => {
    setSelectedTemplateId(templateId);
    setGeneratedMessage(text);
    setGeneratedAdvice('تم اختيار قالب جاهز، يمكنك تعديله أو إرساله مباشرة.');
  };

  const handleQuickCopy = (e: React.MouseEvent, text: string) => {
    e.stopPropagation();
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // 2. Generate with Gemini AI
  const handleGenerateAI = async () => {
    if (!selectedDebtorBalance) {
      setError('يرجى اختيار عميل لديه رصيد مستحق أولاً.');
      return;
    }

    setIsGenerating(true);
    setError('');
    setGeneratedMessage('');
    setGeneratedAdvice('');

    try {
      const response = await fetch('/api/ai', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...getGeminiHeaders(),
        },
        body: JSON.stringify({
          customerName: selectedDebtorBalance.customer.name,
          amount: selectedDebtorBalance.remainingDebt,
          notes: customNotes || selectedDebtorBalance.customer.notes || 'مشتريات بضاعة متنوعة بالآجل',
          tone: tone,
        }),
      });

      const data = await response.json();
      if (!response.ok) {
        throw new Error(data.error || 'حدث خطأ غير متوقع أثناء معالجة الـ AI.');
      }

      setGeneratedMessage(data.message);
      setGeneratedAdvice(data.advice || 'راقب التزام العميل بالسداد في المواعيد المقررة.');
    } catch (e: any) {
      console.error(e);
      setError(e.message || 'فشل الاتصال بالخادم الذكي لتوليد الرسالة.');
    } finally {
      setIsGenerating(false);
    }
  };

  // Auto generate message if guided via URL
  React.useEffect(() => {
    if (
      queryCustomerId && 
      selectedDebtorBalance && 
      selectedDebtorBalance.customer.id === queryCustomerId &&
      hasAutoGeneratedFor !== queryCustomerId
    ) {
      setHasAutoGeneratedFor(queryCustomerId);
      const timer = setTimeout(() => {
        handleGenerateAI();
      }, 500);
      return () => clearTimeout(timer);
    }
  }, [queryCustomerId, selectedDebtorBalance, hasAutoGeneratedFor]);

  const handleCopyToClipboard = () => {
    if (!generatedMessage) return;
    triggerHaptic('success');
    navigator.clipboard.writeText(generatedMessage);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSendWhatsApp = () => {
    if (!selectedDebtorBalance || !generatedMessage) return;
    triggerHaptic('medium');
    
    // Clean and format phone number via shared utility
    const cleanPhone = formatPhoneNumberForUrl(selectedDebtorBalance.customer.phone);
    
    const encodedText = encodeURIComponent(generatedMessage);
    const whatsappUrl = `https://wa.me/${cleanPhone}?text=${encodedText}`;
    
    // Open in a new tab securely
    window.open(whatsappUrl, '_blank', 'noreferrer,noopener');
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 transition-colors">
      
      {/* 1. LEFT CONFIG PANE */}
      <div className="lg:col-span-1 space-y-3">
        <div className="p-4 bg-white rounded-2xl border border-slate-100 shadow-xs space-y-3.5 transition-colors">
          <h3 className="text-xs font-black text-slate-800 flex items-center gap-1.5 transition-colors">
            <MessageSquare className="w-4 h-4 text-emerald-600 transition-colors" />
            تجهيز تذكير المستحقات
          </h3>

          {activeDebtors.length === 0 ? (
            <div className="p-6 text-center text-slate-400 text-[10px] bg-slate-50 rounded-xl transition-colors">
              لا يوجد مدينين حالياً لإرسال مذكرات سداد إليهم! 👍
            </div>
          ) : (
            <div className="space-y-3.5">
              {/* Select Customer */}
              <div>
                <label className="block mb-1 text-[10px] font-black text-slate-400 transition-colors uppercase">اختر العميل:</label>
                <select
                  value={selectedCustomerId}
                  onChange={(e) => {
                    setSelectedCustomerId(e.target.value);
                    setSelectedTemplateId(null);
                    setGeneratedMessage('');
                    setGeneratedAdvice('');
                  }}
                  className="w-full px-3 py-2 text-[11px] font-black bg-slate-50 border border-slate-200 rounded-xl focus:outline-hidden focus:border-emerald-500 focus:bg-white transition-colors cursor-pointer"
                >
                  {activeDebtors.map((d) => (
                    <option key={d.customer.id} value={d.customer.id}>
                      {d.customer.name} ({formatCurrency(d.remainingDebt)})
                    </option>
                  ))}
                </select>
              </div>

              {selectedDebtorBalance && (
                <div className="p-2.5 bg-rose-50/50 rounded-xl border border-rose-100/40 text-[10px] space-y-0.5 transition-colors">
                  <div className="flex justify-between font-black text-slate-700 transition-colors">
                    <span>المبلغ المتبقي:</span>
                    <span className="text-rose-600 font-black">{formatCurrency(selectedDebtorBalance.remainingDebt)}</span>
                  </div>
                </div>
              )}

              <hr className="border-slate-50 transition-colors" />

              {/* Quick Template Presets with Categories */}
              <div className="space-y-2.5">
                <div className="flex items-center justify-between">
                  <span className="block text-[9px] font-black text-slate-400 uppercase tracking-wide transition-colors">قوالب جاهزة:</span>
                  <div className="flex gap-1 overflow-x-auto no-scrollbar pb-1">
                    {categories.map(cat => (
                      <button
                        key={cat}
                        onClick={() => setActiveCategory(cat)}
                        className={`px-2 py-0.5 rounded-lg text-[8px] font-black transition-all whitespace-nowrap cursor-pointer ${
                          activeCategory === cat 
                            ? 'bg-indigo-600 text-white' 
                            : 'bg-slate-100 text-slate-500 hover:bg-slate-200'
                        }`}
                      >
                        {cat}
                      </button>
                    ))}
                  </div>
                </div>
                
                <div className="flex flex-col gap-1.5 max-h-[160px] overflow-y-auto pr-1 no-scrollbar">
                  {filteredTemplates.length === 0 ? (
                    <p className="text-[10px] text-slate-400 text-center py-4">لا توجد قوالب.</p>
                  ) : (
                    filteredTemplates.map((t) => (
                      <div key={t.id} className="relative group">
                        <button
                          onClick={() => handleApplyTemplate(t.id, t.text)}
                          className={`w-full text-right text-[10px] p-2 pl-8 rounded-xl border transition-all cursor-pointer font-black ${
                            selectedTemplateId === t.id
                              ? 'bg-indigo-50 border-indigo-200 text-indigo-700 shadow-xs'
                              : 'bg-slate-50 hover:bg-slate-100 hover:text-indigo-700 border-slate-150 text-slate-600'
                          }`}
                        >
                          <span className="flex items-center gap-1.5">
                            <span className={`w-1 h-1 rounded-full ${
                              t.category === 'مستعجل' ? 'bg-rose-500' : 
                              t.category === 'رسمي' ? 'bg-sky-500' :
                              t.category === 'ودي' ? 'bg-emerald-500' : 'bg-slate-400'
                            }`} />
                            {t.name}
                          </span>
                        </button>
                        <button
                          onClick={(e) => handleQuickCopy(e, t.text)}
                          title="نسخ سريع"
                          className="absolute left-1.5 top-1/2 -translate-y-1/2 p-1 text-slate-300 hover:text-indigo-600 rounded-lg transition-all cursor-pointer"
                        >
                          <Copy className="w-3 h-3" />
                        </button>
                      </div>
                    ))
                  )}
                </div>
              </div>

              <div className="space-y-3 bg-indigo-50/20 p-3 rounded-xl border border-indigo-100/40 transition-colors">
                <span className="block text-[10px] font-black text-indigo-800 flex items-center gap-1 transition-colors">
                  <Sparkles className="w-3.5 h-3.5 text-indigo-600 transition-colors" />
                  مساعد AI الذكي
                </span>

                {/* Tone select */}
                <div>
                  <div className="grid grid-cols-2 gap-1 text-[9px] font-black">
                    <button
                      onClick={() => setTone('friendly')}
                      className={`py-1.5 rounded-lg border text-center cursor-pointer transition-all ${
                        tone === 'friendly' 
                          ? 'bg-indigo-600 text-white border-indigo-600 shadow-xs' 
                          : 'bg-white text-slate-600 border-slate-200 hover:text-slate-800'
                      }`}
                    >
                      😊 ودي
                    </button>
                    <button
                      onClick={() => setTone('firm')}
                      className={`py-1.5 rounded-lg border text-center cursor-pointer transition-all ${
                        tone === 'firm' 
                          ? 'bg-slate-700 text-white border-slate-700 shadow-xs' 
                          : 'bg-white text-slate-600 border-slate-200 hover:text-slate-800'
                      }`}
                    >
                      🛡️ حازم
                    </button>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={handleGenerateAI}
                  disabled={isGenerating || !selectedCustomerId}
                  className="w-full py-2 px-3 rounded-xl text-[10px] font-black text-white bg-indigo-600 hover:bg-indigo-700 transition-all flex items-center justify-center gap-1.5 cursor-pointer disabled:opacity-50 shadow-xs"
                  style={{ backgroundColor: 'var(--brand-color)' }}
                >
                  <Sparkles className="w-3.5 h-3.5" />
                  {isGenerating ? 'جاري الصياغة...' : 'صياغة بـ AI'}
                </button>
              </div>

            </div>
          )}
        </div>
      </div>

      {/* 2. RIGHT PREVIEW BOARD */}
      <div className="lg:col-span-2 space-y-4">
        <div className="p-6 bg-white rounded-2xl border border-slate-100 shadow-xs space-y-5 flex flex-col justify-between min-h-[460px] transition-colors">
          
          <div className="space-y-4">
            <div className="flex items-center justify-between border-b pb-3 transition-colors">
              <h4 className="text-sm font-bold text-slate-800 transition-colors">معاينة الرسالة المتولدة والإرسال</h4>
              <span className="text-[10px] text-slate-400 font-bold transition-colors">تطبيق واتساب</span>
            </div>

            {error && (
              <div className="p-3 bg-red-50 text-red-600 border border-red-150 rounded-xl text-xs font-bold transition-colors">
                {error}
              </div>
            )}

            {/* Simulated Mobile WhatsApp Chat Node */}
            <div className="bg-slate-50 rounded-2xl p-4 md:p-6 border border-slate-150 max-w-lg mx-auto relative overflow-hidden transition-colors">
              <div className="absolute inset-0 bg-repeat opacity-[0.03]" style={{ backgroundImage: "url('https://upload.wikimedia.org/wikipedia/commons/e/e3/WhatsApp_background.png')" }} />
              
              <div className="relative z-10 space-y-4">
                {/* Contact header simulation */}
                <div className="flex items-center gap-2.5 pb-2 border-b border-slate-200/50 transition-colors">
                  <div className="w-8 h-8 rounded-full bg-emerald-100 flex items-center justify-center text-emerald-700 transition-colors">
                    <User className="w-4 h-4" />
                  </div>
                  <div>
                    <h5 className="text-xs font-bold text-slate-800 transition-colors">{selectedDebtorBalance ? selectedDebtorBalance.customer.name : 'اسم العميل'}</h5>
                    <span className="text-[9px] text-slate-400 font-bold tracking-wider transition-colors" dir="ltr">{selectedDebtorBalance ? selectedDebtorBalance.customer.phone : '050xxxxxxx'}</span>
                  </div>
                </div>

                {/* Message display bubble inside simulated phone */}
                <div className="flex items-end justify-start">
                  {!generatedMessage ? (
                    <div className="bg-white p-5 rounded-2xl rounded-tr-none text-slate-400 text-xs text-center border border-slate-100 max-w-sm transition-colors">
                      <p>لم يتم صياغة أي تذكير بعد.</p>
                      <p className="text-[10px] mt-1 text-slate-500">اختر قالباً سريعاً من اليمين أو صغ نص مالي متقن ومحدد بالذكاء الاصطناعي (Gemini) بضغطة زر واحدة.</p>
                    </div>
                  ) : (
                    <div className="bg-emerald-50 text-slate-800 px-4 py-3.5 rounded-2xl rounded-tr-none shadow-2xs text-xs font-semibold whitespace-pre-line leading-relaxed max-w-sm border border-emerald-150/50 transition-colors">
                      {generatedMessage}
                      <span className="block text-left text-[9px] text-slate-400 font-sans mt-2.5 transition-colors" dir="ltr">
                        {new Date().toLocaleTimeString('ar-SA', { hour: '2-digit', minute: '2-digit' })}
                      </span>
                    </div>
                  )}
                </div>
              </div>
            </div>

            {/* Smart Gemini financial recommendation column */}
            {generatedAdvice && (
              <div className="p-4 bg-indigo-50/50 rounded-xl border border-indigo-100/30 text-xs text-indigo-900 space-y-1 transition-colors">
                <span className="font-bold text-[10px] text-indigo-700 uppercase tracking-wide flex items-center gap-1.5 transition-colors">
                  <Sparkles className="w-3.5 h-3.5" />
                  رأي وتوصية مساعد الذكاء المالي للتعامل مع هذا العميل:
                </span>
                <p className="italic transition-colors">{generatedAdvice}</p>
              </div>
            )}
          </div>

          {/* Action Row */}
          <div className="flex items-center gap-3 border-t border-slate-100 pt-4 transition-colors">
            <button
              onClick={handleSendWhatsApp}
              disabled={!generatedMessage}
              className="flex-1 py-3 px-4 font-bold text-xs text-white bg-[#25D366] hover:bg-[#20ba59] active:scale-[0.98] rounded-xl tracking-wide shadow-xs flex items-center justify-center gap-2 transition-all cursor-pointer disabled:opacity-50 disabled:bg-slate-100 disabled:text-slate-400 border border-[#25D366]/10"
            >
              <Send className="w-4.5 h-4.5" />
              مشاركة عبر واتساب
              <ExternalLink className="w-3.5 h-3.5 shrink-0 opacity-80" />
            </button>
            <button
              onClick={handleCopyToClipboard}
              disabled={!generatedMessage}
              className="px-4 py-3 text-xs font-bold text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-xl flex items-center gap-1.5 transition-all cursor-pointer disabled:opacity-50"
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4 text-emerald-600" />
                  تم النسخ!
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  نسخ النص
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
